### ISSUE TITLE
Magic Map for Button Movement

### ISSUE THREAD

**Issue by celseastro** [GenesisMudDiscord/Webclient---JavaScript#6]
How to replace magic map X Y coordinate with red X for magic map through JavaScript.
Input String = mud.gmcp['room.map'].map
How to count character?
How \n works?
How to replace?
How to color?

**Comment by Nadineioes** [comment]
I swapped mud.gmcp['room.map'].map with inbuilt 'exa map', which seems to fix the X problem, next issue is making it a tad prettier
